# Generated by Django 5.2.5 on 2025-08-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysets', '0002_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='querysets.blog')),
                ('theme', models.CharField(max_length=200)),
            ],
            bases=('querysets.blog',),
        ),
    ]
